# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronos', '0004_auto_20160526_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prono',
            old_name='score_visitors',
            new_name='score_visitor',
        ),
    ]
